openapi: 3.1.0
info:
  version: 1.0.0
  title: Foodies app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation of Foodies app
tags:
  - name: Recipes
    description: Operations about recipes.
  - name: Users
    description: User registration, login, and profile operations.
  - name: Areas
    description: Operations about areas.
  - name: Categories
    description: Operations about categories.
  - name: Ingredients
    description: Operations about ingredients.
  - name: Testimonials
    description: Operations about testimonials.
servers:
  - url: https://foodies-back-1.onrender.com
  - url: http://localhost:3000
paths:
  /api/recipes:
    get:
      $ref: ../paths/recipes/get.yaml
    post:
      $ref: ../paths/recipes/post.yaml
  /api/recipes/popular:
    get:
      $ref: ../paths/recipes/popular/get.yaml
  /api/recipes/{id}:
    get:
      $ref: ../paths/recipes/{id}/get.yaml
    delete:
      $ref: ../paths/recipes/{id}/delete.yaml
  /api/recipes/own:
    get:
      $ref: ../paths/recipes/own/get.yaml
  /api/recipes/{id}/favorite:
    post:
      $ref: ../paths/recipes/{id}/favorite/post.yaml
    delete:
      $ref: ../paths/recipes/{id}/favorite/delete.yaml
  /api/recipes/favorites:
    get:
      $ref: ../paths/recipes/favorites/get.yaml
  /api/users/register:
    post:
      $ref: ../paths/users/register/post.yaml
  /api/users/login:
    post:
      $ref: ../paths/users/login/post.yaml
  /api/users/logout:
    post:
      $ref: ../paths/users/logout/post.yaml
  /api/users/me:
    get:
      $ref: ../paths/users/me/get.yaml
  /api/areas:
    get:
      $ref: ../paths/areas/get.yaml
  /api/categories:
    get:
      $ref: ../paths/categories/get.yaml
  /api/ingredients:
    get:
      $ref: ../paths/ingredients/get.yaml
  /api/testimonials:
    get:
      $ref: ../paths/testimonials/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
